### PR TITLE
Scheduled Query Alert

### PR DESCRIPTION
**Pull request by tw3lveparsecs**
Added schedule query alert functionality

### CODE REVIEW

**Comment by tw3lveparsecs** [comment]
@ThorSchutze can you run a review please and see if anything sticks out? I'm sure there is a typo there somewhere lol.
Thanks 👊

**Review by ThorSchutze — DISMISSED** [review]
Looks good. One question, defining variables inside the bicep code. Computed var I get but static? can they be passed from external? Haven't tried hence the question.

**Comment by tw3lveparsecs** [comment]
> Looks good. One question, defining variables inside the bicep code. Computed var I get but static? can they be passed from external? Haven't tried hence the question.

#136 has been raised to review this at a later stage, for now vars are used when a bicep template calls another template.

**Comment by tw3lveparsecs** [comment]
@ThorSchutze didnt realise this PR was still open. Can you review the recent changes for adding activity log alerts please?

**Review by ThorSchutze — APPROVED** [review]
Approved

**Pull request merged**
